ALTER DATABASE "grs-db"
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON)

ALTER TABLE BasicModel
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)

ALTER TABLE IssueReport
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)

ALTER TABLE IssueReportAttachment
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)

ALTER TABLE Series2
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)
